name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      id: lc
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r docs -x \/install
    - name: Fail if there were link errors
      run: exit ${{ steps.lc.outputs.exit_code }}
